from graphviz import Digraph

dot = Digraph('MVP_Workflow')

dot.node('A', 'Plan Idea')
dot.node('B', 'Create Goals')
dot.node('C', 'Create Tasks')
dot.node('D', 'Create Sub-Tasks')
dot.node('E', 'Execute Sub-Task')
dot.node('F', 'Check and Test for Success')
dot.node('G', 'Is Sub-Task Successful?')
dot.node('H', 'Proceed to Next Sub-Task')
dot.node('I', 'Reattempt/Adjust Sub-Task')
dot.node('J', 'Are All Sub-Tasks Completed?')
dot.node('K', 'Proceed to Next Task')
dot.node('L', 'Update Goal Progress')
dot.node('M', 'Are All Goals Achieved?')
dot.node('N', 'Project Completed')
dot.node('O', 'Reevaluate and Adjust Goals/Tasks')

dot.edges(['AB', 'BC', 'CD', 'DE', 'EF', 'FG'])
dot.edge('G', 'H', label='Yes')
dot.edge('G', 'I', label='No')
dot.edge('H', 'J')
dot.edge('I', 'J')
dot.edge('J', 'K', label='Yes')
dot.edge('J', 'D', label='No')
dot.edge('K', 'L')
dot.edge('L', 'M')
dot.edge('M', 'N', label='Yes')
dot.edge('M', 'O', label='No')
dot.edge('O', 'B')

dot.render('mvp_workflow.gv', view=True)
