from graphviz import Digraph

dot = Digraph('GPT_MVP_Workflow')
dot.attr(rankdir='TB', size='20,20', ratio='compress', fontsize='20', fontname='Open Sans')

# Nodes with different shapes and colors
dot.node('0', 'Start', shape='circle', style='filled', fillcolor='white', borderRadius='3')
dot.node('A', 'Plan Idea', shape='ellipse', style='filled', fillcolor='lightblue')
dot.node('B', 'Prioritize Goals\n(using a sophisticated system)', shape='box', style='filled', fillcolor='lightgreen')
dot.node('D', 'Prioritize Tasks\n(using a sophisticated system)', shape='box', style='filled', fillcolor='lightgreen')
dot.node('C', 'Identify Dependencies\n& Blockers', shape='box', style='filled', fillcolor='lightgreen')
dot.node('C1', 'Resolve Dependencies\n& Blockers', shape='box', style='filled', fillcolor='pink', fontsize='18')
dot.node('E', 'Delegate &\nAssign Tasks to GPTs', shape='parallelogram', style='filled', fillcolor='yellow')
dot.node('F', 'Create &\nPrioritize Sub-Tasks', shape='box', style='filled', fillcolor='lightgreen')
dot.node('G', 'Delegate &\nAssign Sub-Tasks to GPTs', shape='parallelogram', style='filled', fillcolor='yellow')
dot.node('H', 'Execute Sub-Task', shape='diamond', style='filled', fillcolor='orange')
dot.node('I', 'Check and\nTest for Success', shape='diamond', style='filled', fillcolor='orange')
dot.node('J', 'Is Sub-Task Successful?', shape='diamond', style='filled', fillcolor='orange')
dot.node('K', 'Proceed to Next Sub-Task', shape='circle', style='filled', fillcolor='gray')
dot.node('L', 'Reattempt/Adjust Sub-Task', shape='circle', style='filled', fillcolor='gray')
dot.node('M', 'Are All Sub-Tasks Completed?', shape='diamond', style='filled', fillcolor='orange')
dot.node('N', 'Proceed to Next Task', shape='circle', style='filled', fillcolor='gray')
dot.node('O', 'Update Goal Progress', shape='parallelogram', style='filled', fillcolor='yellow')
dot.node('P', 'Are All Goals Achieved?', shape='diamond', style='filled', fillcolor='orange')
dot.node('PA', 'Monitor Performance\n& Adjust', shape='hexagon', style='filled', fillcolor='purple', fontsize='18')
dot.node('Q', 'Project Completed', shape='doublecircle', style='filled', fillcolor='lightblue')
dot.node('R', 'Periodic Review & Adjustments', shape='hexagon', style='filled', fillcolor='purple')
dot.node('S', 'Reevaluate & Adjust Goals/Tasks', shape='hexagon', style='filled', fillcolor='purple')
dot.node('T', 'Any Remaining Tasks?', shape='diamond', style='filled', fillcolor='lightblue')
dot.node('U', 'Identify & Resolve\nTask Blockers', shape='box', style='filled', fillcolor='pink', fontsize='18')
dot.node('V', 'Identify & Resolve\nSub-Task Blockers', shape='box', style='filled', fillcolor='pink', fontsize='18')
dot.node('W', 'Review &\nAdjust Tasks', shape='hexagon', style='filled', fillcolor='purple', fontsize='18')
dot.node('X', 'Review &\nAdjust Sub-Tasks', shape='hexagon', style='filled', fillcolor='purple', fontsize='18')
dot.node('Y', 'Instantiate New GPT\nInstances for Adjustments', shape='parallelogram', style='filled', fillcolor='yellow', fontsize='18')
dot.node('Z', 'End (Optional)', shape='circle', style='filled', fillcolor='white')

# Edges
dot.edge('0', 'A')
dot.edges(['AB', 'BC', 'CD', 'DE', 'EF', 'FG', 'GH', 'HI'])
dot.edge('C', 'C1')
dot.edge('C1', 'D')
dot.edge('I', 'J', label='Yes')
dot.edge('J', 'K', label='Yes')
dot.edge('J', 'L', label='No')
dot.edge('K', 'M')
dot.edge('K', 'F')
dot.edge('L', 'M')
dot.edge('N', 'O')
dot.edge('M', 'G', label='No')
dot.edge('M', 'N', label='No')
dot.edge('O', 'P')
dot.edge('P', 'Q', label='Yes')
dot.edge('P', 'S', label='No')
dot.edge('P', 'PA', label='No')
dot.edge('PA', 'S')
dot.edge('S', 'B')
dot.edge('Q', 'R', label='Periodic Review')
dot.edge('R', 'S', label='Adjustments')
dot.edge('M', 'T', label='Yes')
dot.edge('T', 'A', label='No')
dot.edge('T', 'E', label='Yes')
dot.edge('D', 'U')
dot.edge('U', 'E')
dot.edge('F', 'V')
dot.edge('V', 'G')
dot.edge('Q', 'Z', label='Stop', color='red')

# Add double edges for parallelism
dot.edge('E', 'F', style='invis')
dot.edge('F', 'G', style='invis')
dot.edge('G', 'H', style='invis')


# Add edges for review and adjust steps
dot.edge('E', 'W')
dot.edge('W', 'U')
dot.edge('G', 'X')
dot.edge('X', 'V')

# Add edges for instantiating new GPT instances
dot.edge('W', 'Y')
dot.edge('Y', 'E')
dot.edge('X', 'Y')
dot.edge('Y', 'G')

# Add descriptions
dot.node('Parallel1', 'Goals can be\nexecuted in parallel', shape='note', fontsize='14', color='blue')
dot.edge('Parallel1', 'B', style='dashed', arrowhead='vee', color='blue')
dot.node('Parallel2', 'Sub-tasks can be\nexecuted in parallel', shape='note', fontsize='14', color='blue')
dot.edge('Parallel2', 'F', style='dashed', arrowhead='vee', color='blue')

dot.render('gpt_mvp_workflow', view=True, format='svg')